"""Modified Table Name

Revision ID: 5638ae84317f
Revises: d768ff996d7d
Create Date: 2024-07-06 23:19:14.218026

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5638ae84317f'
down_revision: Union[str, None] = 'd768ff996d7d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('TestMetadata',
    sa.Column('metadata_uuid', sa.String(length=50), nullable=False),
    sa.Column('owner', sa.String(length=255), nullable=True),
    sa.Column('doa', sa.String(length=20), nullable=True),
    sa.Column('with_tgen', sa.String(length=3), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('product', sa.String(length=50), nullable=True),
    sa.Column('interface', sa.String(length=50), nullable=True),
    sa.Column('script_id', sa.String(length=10), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('software_version', sa.String(length=20), nullable=True),
    sa.Column('simulator_compatible', sa.String(length=3), nullable=True),
    sa.PrimaryKeyConstraint('metadata_uuid')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('TestMetadata')
    # ### end Alembic commands ###
